### ISSUE TITLE
box_positions in iJO1366

### ISSUE THREAD

**Issue by VonAlphaBisZulu** [klamt-lab/cnapy#154]
Use this CNA model with adapted box_positions as iJO1366 model. (rename to iJO1366.cna). Reaction boxes will show at the right positions.

[iJO1366.zip](https://github.com/klamt-lab/cnapy/files/6143580/iJO1366.zip)

**Comment by sthiele** [comment]
Thanks, this looks beautiful.
BTW there is an repository for the cnapy-projects here https://github.com/cnapy-org/cnapy-projects. If you want to submit a PR.

**Comment by sthiele** [comment]
There is a box position for ```Growth``` but the model has no reaction with this id. What would be the equivalent reaction id? ```BIOMASS_Ec_iJO1366_core_53p95M``` or maybe ```BIOMASS_Ec_iJO1366_WT_53p95M``` ?

**Comment by VonAlphaBisZulu** [comment]
It's BIOMASS_Ec_iJO1366_core_53p95M.

Reaction box was added in pull request, together with CNApy model for iML1515:
https://github.com/cnapy-org/cnapy-projects/pull/2
